### PR TITLE
feat(diff): generates diff from a patch

### PR DESCRIPTION
**Pull request by tdurieux**
This feature was easier to develop with spoon 5.5.0.
This PR also contains the required change to support this new version.

### CODE REVIEW

**Comment by monperrus** [comment]
travis fails

**Comment by tdurieux** [comment]
I know, the patch generator is buggy.

**Comment by monperrus** [comment]
ping?

**Comment by tdurieux** [comment]
@monperrus pong

Currently, Nopol does not create any additional file

**Comment by monperrus** [comment]
Can it create one?

**Pull request merged**
