### PR TITLE
Nopol works on Java 11

### LINKED ISSUE #211: Support Java 11
Currently Java >8 support is limited due to the `tools.jar` dependency.

It would be important to fix these compatibility issues as Nopol's usage in https://github.com/eclipse/repairnator will be limited when it moves to Java 11.

### PR DESCRIPTION
**Pull request by andre15silva**
fix #211 

Testing in CI env. Compilation is working, tests are not (locally).

### CODE REVIEW

**Comment by andre15silva** [comment]
There was a bug there due to a change in the API. `URLClassLoader` is no longer a super class for the system `ClassLoader`s.

I found a workaround to do this (See https://cgjennings.ca/articles/java-9-dynamic-jar-loading/)

Dynamoth should now be working. Its tested are all green. 

There is a bug, however, with GZoltar. Haven't found a solution for that.

TODO:
- load javaagent in normal execution
- fix GZoltar

**Comment by monperrus** [comment]
Waiting for https://github.com/SpoonLabs/nopol/pull/220 (FL based on Flacoco) which is a blocker for the one

**Comment by monperrus** [comment]
now that we have Flacoco, are we ready to support Java 11?

**Comment by monperrus** [comment]
Spent some long hours here. It's now working.

Notes:

* in Java 11, `tools.jar` has been renamed and even has a new format (JMOD), it's now `jdk.jdi.jmod`
* some TSE and Defects4J bugs (in particular Lang) requires java source code version 3 or 4. While 3 or 4 was still supported in a JVM 8, they have been dropped in 11. Consequently, we lose them all as test case. Yet, I ported 4 of them manually (Lang44, Lang51, Lang53, Lang58), and pushed them to defects4j-repair, eg https://github.com/Spirals-Team/defects4j-repair/tree/Lang58-Java6
*  the trick with the classloader of `cgjennings` was nice, eventually I found a way to remove the need for that
* porting nopol-ui-intellij was tedious because of the stacked and interleaved problems of upgrading the JVM version, the Gradle version, the IntelliJ version

I'd say it's done,, and this opens the door for getting https://ci.inria.fr/sos/job/Nopol/ green again

**Pull request merged**
