### PR TITLE
add Flacoco as fault localization engine

### LINKED ISSUE #216: integrate flacoco
this should even be the default FL mode

### PR DESCRIPTION
**Pull request by andre15silva**
fixes #216

### CODE REVIEW

**Comment by andre15silva** [comment]
Blocked by https://github.com/SpoonLabs/flacoco/pull/81

**Comment by andre15silva** [comment]
There is a compatibility issue between `flacoco` and `nopol`.

`flacoco` requires access to the binaries, and `nopol` does not have this information available in any place other than being embedded in the classpath itself

**Comment by monperrus** [comment]
interesting, to be discussed.

**Comment by andre15silva** [comment]
> interesting, to be discussed.

FYI, the new online mode (https://github.com/SpoonLabs/flacoco/pull/86) does not need access to the binaries, only the names of the classes to include/exclude. Since we have access to the source files here in `nopol` that is taken care of.

**Comment by andre15silva** [comment]
`cm1` is failing due to some bug in jacoco. See https://github.com/jacoco/jacoco/issues/1223

same thing with `cl4`. See https://github.com/jacoco/jacoco/issues/1223#issuecomment-925132786

**Comment by monperrus** [comment]
interesting

**Comment by andre15silva** [comment]
In the `cm5` bug we find the correct line, but nopol itself isn't able to generate a patch.

From the paper, the buggy code is `        if (u * v == 0) {
`, which corresponds to `org.apache.commons.math.util.MathUtils:412`

This line is included in the results for both GZoltar and Flacoco (flacoco results below):

```
Failing tests:
[Manual]TestMethod=org.apache.commons.math.util.MathUtilsTest#testGcd_0
[Manual]TestMethod=org.apache.commons.math.util.MathUtilsTest#testGcd_3
[Manual]TestMethod=org.apache.commons.math.util.MathUtilsTest#testGcd_1
[Manual]TestMethod=org.apache.commons.math.util.MathUtilsTest#testGcd_4
SourceLocation org.apache.commons.math.util.MathUtils:413:0.5547001962252291
SourceLocation org.apache.commons.math.util.MathUtils:412:0.30151134457776363
```

**Comment by andre15silva** [comment]
Also note that Flacoco is not facing the same issue as GZoltar in #223 , and is able to compute the right failing tests.

**Comment by monperrus** [comment]
is Nopol in SMT or Dynamoth mode in this run?

**Comment by andre15silva** [comment]
> is Nopol in SMT or Dynamoth mode in this run?

`SMT` is the default, but with I've tried with `Dynamoth` and it doesn't find a patch for `cm5` either.

**Comment by andre15silva** [comment]
- `cl2`: Not working due to a bug in Jacoco (https://github.com/jacoco/jacoco/issues/1223#issuecomment-926636606)
- `cl4`: Not working due to a bug in Jacoco (https://github.com/jacoco/jacoco/issues/1223#issuecomment-925132786)
- `cm1`: Not working due to a bug in Jacoco (https://github.com/jacoco/jacoco/issues/1223#issue-1004229754)
- `cm5`: Not working due to a bug in Nopol (https://github.com/SpoonLabs/nopol/pull/220#issuecomment-925976387)

**Comment by monperrus** [comment]
Per our discussion, will merge when CI is green.

**Comment by andre15silva** [comment]
For the record, `cl4` works if we use https://github.com/jacoco/jacoco/pull/321

**Comment by andre15silva** [comment]
~~`cm7` is failing with flacoco `1.0.0` but works with flacoco `0.0.1-SNAPSHOT`~~

**Comment by andre15silva** [comment]
- [x] Fix `example7Fix`
- [x] Use GZoltar for the ignored TSE bugs
- [x] update to flacoco new release

**Comment by andre15silva** [comment]
Ready for review @monperrus

**Comment by monperrus** [comment]
Yeah, that's great @andre15silva thanks.

**Pull request merged**
