### PR TITLE
WIP: Removed com.sun.tools from System Scope

### PR DESCRIPTION
**Pull request by lapplislazuli**
Hi, 

this is an issue originating from https://github.com/SpoonLabs/astor/issues/243 and similar to #211 .

The build proceeds fine, and when I use the 0.3-Snapshot Astor also builds without issues. 
Astors tests run too, but some of them are failing. 

However I must admit that the tests are failing, but I have no clue which ones are the serious ones. 
Second look would be great @martinezmatias .

### CODE REVIEW

**Comment by martinezmatias** [comment]
Hi @Twonki 
Thanks for the PR.

> However I must admit that the tests are failing, but I have no clue which ones are the serious ones.

I would say that some may fail due to the lack of the dependency on runtime.

**Comment by lapplislazuli** [comment]
Hmm, yes indeed, many classes actually need the JDI. 

Some of these can be migrated using com.java.reflect, but others can't like com.sun.jdi.Value. 
It would definetly need a bigger migration. 

In terms of Astor, how important is Nopol for it? Is it just a plugin, or is it required for logic? @martinezmatias

**Comment by martinezmatias** [comment]
Hi @Twonki 

> In terms of Astor, how important is Nopol for it? Is it just a plugin, or is it required for logic? @martinezmatias

It was used by some repair prototipes included in the framework (which have been under working), but not  used by any of the main repair approaches we used in the experiments (Cardumen, jGenprog, jKali, etc). You can open an issue on Astor to discuss about that

**Comment by lapplislazuli** [comment]
Will do!

**Comment by monperrus** [comment]
Thanks for the update.

FTR, see https://github.com/SpoonLabs/nopol/issues/211#issuecomment-800312228

**Pull request closed without merging**
