### PR TITLE
Make build(String[]) private to have only one accessor to the build API.

### PR DESCRIPTION
**Pull request by surli**

### CODE REVIEW

**Comment by tdurieux** [comment]
This API is used

**Comment by tdurieux** [comment]
You will broke some clients by removing build(tests).

**Comment by surli** [comment]
> You will broke some clients by removing build(tests).

You mean inside Nopol? I already checked and replaced them by build().

**Comment by tdurieux** [comment]
nop outside users.
It is not possible to specify which tests to execute after your change

**Comment by surli** [comment]
> It is not possible to specify which tests to execute after your change

Yes it is: through ProjectReference... https://github.com/SpoonLabs/nopol/pull/96/files#diff-71b3944bd8ca2360cfe354590ec52a58R73

**Comment by tdurieux** [comment]
But it is not used in the Main class

**Comment by surli** [comment]
As @tdurieux said the ProjectReference was not used everywhere leading to errors on this PR. 
So I decided to force the usage of ProjectReference by removing the second constructor in NoPol.

**Pull request merged**
